In [44]:
import pandas as pd

In [45]:
df = pd.read_table('http://bit.ly/chiporders')

In [17]:
df.to_excel('data.xlsx')

In [22]:
print(df.head())
print(df.tail())
df.sample(5)

   order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa
1         1         1                                   Izze
2         1         1                       Nantucket Nectar
3         1         1  Chips and Tomatillo-Green Chili Salsa
4         2         2                           Chicken Bowl

                                  choice_description item_price
0                                                NaN     $2.39
1                                       [Clementine]     $3.39
2                                            [Apple]     $3.39
3                                                NaN     $2.39
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
      order_id  quantity           item_name  \
4617      1833         1       Steak Burrito
4618      1833         1       Steak Burrito
4619      1834         1  Chicken Salad Bowl
4620      1834         1  Chicken Salad Bowl
4621      1834         1  Chicken Salad Bowl

                                     choice_description item_price
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

,order_id,quantity,item_name,choice_description,item_price
4240,1692,1,Canned Soft Drink,[Diet Coke],$1.25
1396,567,1,Canned Soda,[Coca Cola],$1.09
3241,1298,1,Chips and Guacamole,NaN,$4.45
852,351,1,Chips and Guacamole,NaN,$4.45
3772,1511,1,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75

In [23]:
df.shape

(4622, 5)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   object
 3   choice_description  3376 non-null   object
 4   item_price          4622 non-null   object
dtypes: int64(2), object(3)
memory usage: 180.7+ KB

In [25]:
df.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

In [36]:
print(df.loc[:10, ['order_id', 'quantity', 'item_name']])
print()
print(df.iloc[:10, 0:3])

    order_id  quantity                              item_name
0          1         1           Chips and Fresh Tomato Salsa
1          1         1                                   Izze
2          1         1                       Nantucket Nectar
3          1         1  Chips and Tomatillo-Green Chili Salsa
4          2         2                           Chicken Bowl
5          3         1                           Chicken Bowl
6          3         1                          Side of Chips
7          4         1                          Steak Burrito
8          4         1                       Steak Soft Tacos
9          5         1                          Steak Burrito
10         5         1                    Chips and Guacamole

   order_id  quantity                              item_name
0         1         1           Chips and Fresh Tomato Salsa
1         1         1                                   Izze
2         1         1                       Nantucket Nectar
3         1         1  Chips and Tomatillo-Green Chili Salsa
4         2         2                           Chicken Bowl
5         3         1                           Chicken Bowl
6         3         1                          Side of Chips
7         4         1                          Steak Burrito
8         4         1                       Steak Soft Tacos
9         5         1                          Steak Burrito

In [41]:
df.item_name[:10]

0             Chips and Fresh Tomato Salsa
1                                     Izze
2                         Nantucket Nectar
3    Chips and Tomatillo-Green Chili Salsa
4                             Chicken Bowl
5                             Chicken Bowl
6                            Side of Chips
7                            Steak Burrito
8                         Steak Soft Tacos
9                            Steak Burrito
Name: item_name, dtype: object

In [58]:
print(df.nunique())
df['item_name'].unique()

order_id              1834
quantity                 9
item_name               50
choice_description    1043
item_price              78
dtype: int64

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos', 'Steak Salad',
       'Chips and Mild Fresh Tomato Salsa', 'Veggie Soft Tacos',
       'Carnitas Salad Bowl', 'Barbacoa Salad Bowl', 'Salad',
       'Veggie Crispy Tacos', 'Veggie Salad', 'Carnitas Salad'],
      dtype=object)

In [63]:
print(df.count())
print()
print(df.value_counts())
print()
print(df['item_name'].value_counts().head())

order_id              4622
quantity              4622
item_name             4622
choice_description    3376
item_price            4622
dtype: int64

order_id  quantity  item_name             choice_description                                                                       item_price
926       1         Chicken Bowl          [Roasted Chili Corn Salsa, [Fajita Vegetables, Rice, Cheese, Sour Cream, Lettuce]]       $8.75         3
1011      1         Canned Soft Drink     [Coke]                                                                                   $1.25         3
724       1         Canned Soft Drink     [Coke]                                                                                   $1.25         3
1647      1         Chicken Bowl          [Fresh Tomato Salsa, [Fajita Vegetables, Rice, Cheese, Sour Cream, Guacamole, Lettuce]]  $11.25        2
1778      1         Canned Soft Drink     [Lemonade]                                                                               $1.25         2
                                                                                                                                                ..
1         1         Nantucket Nectar      [Apple]                                                                                  $3.39         1
                    Izze                  [Clementine]                                                                             $3.39         1
1834      1         Chicken Salad Bowl    [Fresh Tomato Salsa, [Fajita Vegetables, Pinto Beans, Lettuce]]                          $8.75         1
6         1         Chicken Crispy Tacos  [Roasted Chili Corn Salsa, [Fajita Vegetables, Rice, Black Beans, Cheese, Sour Cream]]   $8.75         1
1827      1         Canned Soft Drink     [Diet Coke]                                                                              $1.25         1
Name: count, Length: 3335, dtype: int64

item_name
Chicken Bowl           726
Chicken Burrito        553
Chips and Guacamole    479
Steak Burrito          368
Canned Soft Drink      301
Name: count, dtype: int64

In [70]:
print(df.item_name.mode())
print()
print(df.quantity.mean())

0    Chicken Bowl
Name: item_name, dtype: object

1.0757247944612722

In [75]:
print(df[['order_id', 'quantity']].head(10))

   order_id  quantity
0         1         1
1         1         1
2         1         1
3         1         1
4         2         2
5         3         1
6         3         1
7         4         1
8         4         1
9         5         1

In [77]:
print(df.loc[3:10, ['order_id', 'item_name']])

    order_id                              item_name
3          1  Chips and Tomatillo-Green Chili Salsa
4          2                           Chicken Bowl
5          3                           Chicken Bowl
6          3                          Side of Chips
7          4                          Steak Burrito
8          4                       Steak Soft Tacos
9          5                          Steak Burrito
10         5                    Chips and Guacamole

In [82]:
print(df.loc[10]) # complete row

order_id                                5
quantity                                1
item_name             Chips and Guacamole
choice_description                    NaN
item_price                         $4.45
Name: 10, dtype: object

In [88]:
print(df.loc[2:7, ['order_id', 'item_name']])

   order_id                              item_name
2         1                       Nantucket Nectar
3         1  Chips and Tomatillo-Green Chili Salsa
4         2                           Chicken Bowl
5         3                           Chicken Bowl
6         3                          Side of Chips
7         4                          Steak Burrito

In [ ]:
print(df.loc[:, ['order_id']])

      order_id
0            1
1            1
2            1
3            1
4            2
...        ...
4617      1833
4618      1833
4619      1834
4620      1834
4621      1834

[4622 rows x 1 columns]

In [98]:
print(df.iloc[1:10, 0:3])

   order_id  quantity                              item_name
1         1         1                                   Izze
2         1         1                       Nantucket Nectar
3         1         1  Chips and Tomatillo-Green Chili Salsa
4         2         2                           Chicken Bowl
5         3         1                           Chicken Bowl
6         3         1                          Side of Chips
7         4         1                          Steak Burrito
8         4         1                       Steak Soft Tacos
9         5         1                          Steak Burrito

In [32]:
print(df.set_index('order_id').iloc[:,:3].head(10))
print(df.set_index('order_id').head(20))

          quantity                              item_name  \
order_id
1                1           Chips and Fresh Tomato Salsa
1                1                                   Izze
1                1                       Nantucket Nectar
1                1  Chips and Tomatillo-Green Chili Salsa
2                2                           Chicken Bowl
3                1                           Chicken Bowl
3                1                          Side of Chips
4                1                          Steak Burrito
4                1                       Steak Soft Tacos
5                1                          Steak Burrito

                                         choice_description
order_id
1                                                       NaN
1                                              [Clementine]
1                                                   [Apple]
1                                                       NaN
2         [Tomatillo-Red Chili Salsa (Hot), [Black Beans...
3         [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...
3                                                       NaN
4         [Tomatillo Red Chili Salsa, [Fajita Vegetables...
4         [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...
5         [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...
          quantity                              item_name  \
order_id
1                1           Chips and Fresh Tomato Salsa
1                1                                   Izze
1                1                       Nantucket Nectar
1                1  Chips and Tomatillo-Green Chili Salsa
2                2                           Chicken Bowl
3                1                           Chicken Bowl
3                1                          Side of Chips
4                1                          Steak Burrito
4                1                       Steak Soft Tacos
5                1                          Steak Burrito
5                1                    Chips and Guacamole
6                1                   Chicken Crispy Tacos
6                1                     Chicken Soft Tacos
7                1                           Chicken Bowl
7                1                    Chips and Guacamole
8                1  Chips and Tomatillo-Green Chili Salsa
8                1                        Chicken Burrito
9                1                        Chicken Burrito
9                2                            Canned Soda
10               1                           Chicken Bowl

                                         choice_description item_price
order_id
1                                                       NaN     $2.39
1                                              [Clementine]     $3.39
1                                                   [Apple]     $3.39
1                                                       NaN     $2.39
2         [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
3         [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98
3                                                       NaN     $1.69
4         [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75
4         [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25
5         [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25
5                                                       NaN     $4.45
6         [Roasted Chili Corn Salsa, [Fajita Vegetables,...     $8.75
6         [Roasted Chili Corn Salsa, [Rice, Black Beans,...     $8.75
7         [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...    $11.25
7                                                       NaN     $4.45
8                                                       NaN     $2.39
8         [Tomatillo-Green Chili Salsa (Medium), [Pinto ...     $8.49
9         [Fresh Tomato Salsa (Mild), [Black Beans, Rice...     $8.49
9                                                  [Sprite]     $2.18
10        [Tomatillo Red Chili Salsa, [Fajita Vegetables...     $8.75

In [38]:
print(df.choice_description.isnull().head(20))
print(df.isna().iloc[:10,:])

0      True
1     False
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14     True
15     True
16    False
17    False
18    False
19    False
Name: choice_description, dtype: bool
   order_id  quantity  item_name  choice_description  item_price
0     False     False      False                True       False
1     False     False      False               False       False
2     False     False      False               False       False
3     False     False      False                True       False
4     False     False      False               False       False
5     False     False      False               False       False
6     False     False      False                True       False
7     False     False      False               False       False
8     False     False      False               False       False
9     False     False      False               False       False

In [44]:
print(df[df.choice_description.isnull()].head(10))
print(df.choice_description.isnull().head(10))

    order_id  quantity                              item_name  \
0          1         1           Chips and Fresh Tomato Salsa
3          1         1  Chips and Tomatillo-Green Chili Salsa
6          3         1                          Side of Chips
10         5         1                    Chips and Guacamole
14         7         1                    Chips and Guacamole
15         8         1  Chips and Tomatillo-Green Chili Salsa
20        10         1                    Chips and Guacamole
25        13         1           Chips and Fresh Tomato Salsa
30        15         1  Chips and Tomatillo-Green Chili Salsa
32        16         1                          Side of Chips

   choice_description item_price
0                 NaN     $2.39
3                 NaN     $2.39
6                 NaN     $1.69
10                NaN     $4.45
14                NaN     $4.45
15                NaN     $2.39
20                NaN     $4.45
25                NaN     $2.39
30                NaN     $2.39
32                NaN     $1.69
0     True
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9    False
Name: choice_description, dtype: bool

In [47]:
print(df.isnull().sum())

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [50]:
print(df.choice_description.isnull().head(10))
print(df.choice_description.fillna('boss').head(10))

0     True
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9    False
Name: choice_description, dtype: bool
0                                                 boss
1                                         [Clementine]
2                                              [Apple]
3                                                 boss
4    [Tomatillo-Red Chili Salsa (Hot), [Black Beans...
5    [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...
6                                                 boss
7    [Tomatillo Red Chili Salsa, [Fajita Vegetables...
8    [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...
9    [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...
Name: choice_description, dtype: object

In [61]:
print(df.order_id.value_counts())

order_id
926     23
1483    14
205     12
759     11
691     11
        ..
60       1
66       1
72       1
1813     1
2        1
Name: count, Length: 1834, dtype: int64

In [62]:
print(df.order_id.mode())

0    926
Name: order_id, dtype: int64

In [69]:
print(df.dropna(axis=0))

      order_id  quantity           item_name  \
1            1         1                Izze
2            1         1    Nantucket Nectar
4            2         2        Chicken Bowl
5            3         1        Chicken Bowl
7            4         1       Steak Burrito
...        ...       ...                 ...
4617      1833         1       Steak Burrito
4618      1833         1       Steak Burrito
4619      1834         1  Chicken Salad Bowl
4620      1834         1  Chicken Salad Bowl
4621      1834         1  Chicken Salad Bowl

                                     choice_description item_price
1                                          [Clementine]     $3.39
2                                               [Apple]     $3.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
5     [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98
7     [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75
...                                                 ...        ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

[3376 rows x 5 columns]

In [76]:
print(df.drop(columns=['quantity', 'item_name'], axis=1).head(10))
print(df.head(10))

   order_id                                 choice_description item_price
0         1                                                NaN     $2.39
1         1                                       [Clementine]     $3.39
2         1                                            [Apple]     $3.39
3         1                                                NaN     $2.39
4         2  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
5         3  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98
6         3                                                NaN     $1.69
7         4  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75
8         4  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25
9         5  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25
   order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa
1         1         1                                   Izze
2         1         1                       Nantucket Nectar
3         1         1  Chips and Tomatillo-Green Chili Salsa
4         2         2                           Chicken Bowl
5         3         1                           Chicken Bowl
6         3         1                          Side of Chips
7         4         1                          Steak Burrito
8         4         1                       Steak Soft Tacos
9         5         1                          Steak Burrito

                                  choice_description item_price
0                                                NaN     $2.39
1                                       [Clementine]     $3.39
2                                            [Apple]     $3.39
3                                                NaN     $2.39
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98
6                                                NaN     $1.69
7  [Tomatillo Red Chili Salsa, [Fajita Vegetables...    $11.75
8  [Tomatillo Green Chili Salsa, [Pinto Beans, Ch...     $9.25
9  [Fresh Tomato Salsa, [Rice, Black Beans, Pinto...     $9.25

In [79]:
print(df.head(5))
print(df.drop(2, ).head(5))

   order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa
1         1         1                                   Izze
2         1         1                       Nantucket Nectar
3         1         1  Chips and Tomatillo-Green Chili Salsa
4         2         2                           Chicken Bowl

                                  choice_description item_price
0                                                NaN     $2.39
1                                       [Clementine]     $3.39
2                                            [Apple]     $3.39
3                                                NaN     $2.39
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
   order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa
1         1         1                                   Izze
3         1         1  Chips and Tomatillo-Green Chili Salsa
4         2         2                           Chicken Bowl
5         3         1                           Chicken Bowl

                                  choice_description item_price
0                                                NaN     $2.39
1                                       [Clementine]     $3.39
3                                                NaN     $2.39
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98

In [91]:
# print(df.dropna(how='all'))
print(df[df.isna().all(axis=1) == True])

Empty DataFrame
Columns: [order_id, quantity, item_name, choice_description, item_price]
Index: []

In [111]:
print(df['item_name'].duplicated().head(10), df['item_name'].head(15))

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
8    False
9     True
Name: item_name, dtype: bool 0              Chips and Fresh Tomato Salsa
1                                      Izze
2                          Nantucket Nectar
3     Chips and Tomatillo-Green Chili Salsa
4                              Chicken Bowl
5                              Chicken Bowl
6                             Side of Chips
7                             Steak Burrito
8                          Steak Soft Tacos
9                             Steak Burrito
10                      Chips and Guacamole
11                     Chicken Crispy Tacos
12                       Chicken Soft Tacos
13                             Chicken Bowl
14                      Chips and Guacamole
Name: item_name, dtype: object

In [9]:
print(df.drop_duplicates)

<bound method DataFrame.drop_duplicates of       order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa
1            1         1                                   Izze
2            1         1                       Nantucket Nectar
3            1         1  Chips and Tomatillo-Green Chili Salsa
4            2         2                           Chicken Bowl
...        ...       ...                                    ...
4617      1833         1                          Steak Burrito
4618      1833         1                          Steak Burrito
4619      1834         1                     Chicken Salad Bowl
4620      1834         1                     Chicken Salad Bowl
4621      1834         1                     Chicken Salad Bowl

                                     choice_description item_price
0                                                   NaN     $2.39
1                                          [Clementine]     $3.39
2                                               [Apple]     $3.39
3                                                   NaN     $2.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
...                                                 ...        ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

[4622 rows x 5 columns]>

In [11]:
print(df.shape)
print(df.duplicated().shape)

(4622, 5)
(4622,)

In [16]:
print(df.item_name.head(10))
print(df.item_name.str.upper().head(10))
print(df.item_name.str.lower().head(10))

0             Chips and Fresh Tomato Salsa
1                                     Izze
2                         Nantucket Nectar
3    Chips and Tomatillo-Green Chili Salsa
4                             Chicken Bowl
5                             Chicken Bowl
6                            Side of Chips
7                            Steak Burrito
8                         Steak Soft Tacos
9                            Steak Burrito
Name: item_name, dtype: object
0             CHIPS AND FRESH TOMATO SALSA
1                                     IZZE
2                         NANTUCKET NECTAR
3    CHIPS AND TOMATILLO-GREEN CHILI SALSA
4                             CHICKEN BOWL
5                             CHICKEN BOWL
6                            SIDE OF CHIPS
7                            STEAK BURRITO
8                         STEAK SOFT TACOS
9                            STEAK BURRITO
Name: item_name, dtype: object
0             chips and fresh tomato salsa
1                                     izze
2                         nantucket nectar
3    chips and tomatillo-green chili salsa
4                             chicken bowl
5                             chicken bowl
6                            side of chips
7                            steak burrito
8                         steak soft tacos
9                            steak burrito
Name: item_name, dtype: object

In [19]:
print(df.item_price.head(10))
print(df.item_price.str.replace('$', 'chapri').head(10))

0     $2.39
1     $3.39
2     $3.39
3     $2.39
4    $16.98
5    $10.98
6     $1.69
7    $11.75
8     $9.25
9     $9.25
Name: item_price, dtype: object
0     chapri2.39
1     chapri3.39
2     chapri3.39
3     chapri2.39
4    chapri16.98
5    chapri10.98
6     chapri1.69
7    chapri11.75
8     chapri9.25
9     chapri9.25
Name: item_price, dtype: object

In [23]:
print(df.item_price.str.replace('$', '').astype('float'))

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [76]:
print(df.drop(columns=['item_name', 'item_price', 'quantity'], axis=0).head())
print(df.head())
print(df.drop(3).head())

   order_id                                 choice_description
0         1                                                NaN
1         1                                       [Clementine]
2         1                                            [Apple]
3         1                                                NaN
4         2  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...
   order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa
1         1         1                                   Izze
2         1         1                       Nantucket Nectar
3         1         1  Chips and Tomatillo-Green Chili Salsa
4         2         2                           Chicken Bowl

                                  choice_description item_price
0                                                NaN     $2.39
1                                       [Clementine]     $3.39
2                                            [Apple]     $3.39
3                                                NaN     $2.39
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
   order_id  quantity                     item_name  \
0         1         1  Chips and Fresh Tomato Salsa
1         1         1                          Izze
2         1         1              Nantucket Nectar
4         2         2                  Chicken Bowl
5         3         1                  Chicken Bowl

                                  choice_description item_price
0                                                NaN     $2.39
1                                       [Clementine]     $3.39
2                                            [Apple]     $3.39
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
5  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...    $10.98

In [82]:

# Sample DataFrames with the same column names 
data1 = {'A': [1, 2, 3], 'B':[4, 5, 6], 'C':[1,2,3]} 
data2 = {'A': [7, 8, 9], 'B': [10, 11, 12], 'D':[1,2,3]} 
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

print()
print(data1)
print()
print(data2)
 
# Concatenate df1 and df2 horizontally (along columns) with same column names
horizontal_concat = pd.concat([df1, df2], axis=1)
 
# Display the concatenated DataFrame 
print(horizontal_concat)

{'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [1, 2, 3]}

{'A': [7, 8, 9], 'B': [10, 11, 12], 'D': [1, 2, 3]}
   A  B  C  A   B  D
0  1  4  1  7  10  1
1  2  5  2  8  11  2
2  3  6  3  9  12  3

In [111]:
 # Sample DataFrame
data = {'Class': ['A', 'B', 'A', 'B', 'A', 'B'],
        'Gender': ['Male', 'Male', 'Female', 'Female', 'Male', 'Female'],
        'Math_Score': [85, 92, 78, 89, 90, 86],
        'English_Score': [88, 94,80, 92, 92, 88],
        'Physics_Score': [78, 90, 85, 92, 88, 84]}

df = pd.DataFrame(data)
 
# Grouping by 'Category'
grouped_data = df.groupby(['Gender', 'Class'])
print(grouped_data.mean())

              Math_Score  English_Score  Physics_Score
Gender Class
Female A            78.0           80.0           85.0
       B            87.5           90.0           88.0
Male   A            87.5           90.0           83.0
       B            92.0           94.0           90.0

In [91]:
print(grouped_data.Math_Score.agg(['mean', 'min', 'max']))

              mean  min  max
Gender Class
Female A      78.0   78   78
       B      87.5   86   89
Male   A      87.5   85   90
       B      92.0   92   92

In [92]:
print(grouped_data.agg({'Math_Score':['mean', 'min', 'max'], 'Physics_Score':['sum', 'max', 'min']}))

             Math_Score         Physics_Score
                   mean min max           sum max min
Gender Class
Female A           78.0  78  78            85  85  85
       B           87.5  86  89           176  92  84
Male   A           87.5  85  90           166  88  78
       B           92.0  92  92            90  90  90

In [93]:
df.columns

Index(['Class', 'Gender', 'Math_Score', 'English_Score', 'Physics_Score'], dtype='object')

In [94]:
print(df.corr)

<bound method DataFrame.corr of   Class  Gender  Math_Score  English_Score  Physics_Score
0     A    Male          85             88             78
1     B    Male          92             94             90
2     A  Female          78             80             85
3     B  Female          89             92             92
4     A    Male          90             92             88
5     B  Female          86             88             84>

In [118]:
print(df)
print(df.sort_values(by=['Math_Score'], ascending=True))
print(df.sort_values(by=['Math_Score', 'English_Score'], ascending=[True, True]))

  Class  Gender  Math_Score  English_Score  Physics_Score
0     A    Male          85             88             78
1     B    Male          92             94             90
2     A  Female          78             80             85
3     B  Female          89             92             92
4     A    Male          90             92             88
5     B  Female          86             88             84
  Class  Gender  Math_Score  English_Score  Physics_Score
2     A  Female          78             80             85
0     A    Male          85             88             78
5     B  Female          86             88             84
3     B  Female          89             92             92
4     A    Male          90             92             88
1     B    Male          92             94             90
  Class  Gender  Math_Score  English_Score  Physics_Score
2     A  Female          78             80             85
0     A    Male          85             88             78
5     B  Female          86             88             84
3     B  Female          89             92             92
4     A    Male          90             92             88
1     B    Male          92             94             90